pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dangeorge23/notes-app:latest"
    }

    stages {
        
        stage('Clone Code') {
            steps {
                echo 'Cloning code from github repository'
                git branch: 'main', url: 'https://github.com/dangeorge/Django-app-on-EC2-using-Jenkins-pipeline.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building'
                script {
                sh 'cd django_notes_app && docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }
        stage('Push to Docker Hub') {
            

            steps {
                echo 'Pushing image to docker hub'
                script {
                docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-login') {
                def app = docker.image("${DOCKER_IMAGE}")
                app.push()
                }
               }
            }
        }
        stage('Deployment') {
            steps {
                echo 'Deploying the container'
                sh "cd django_notes_app docker-compose down && docker-compose up -d"
            }
        }
    }
}